# Generated by Django 5.2.5 on 2025-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="full name"
            ),
        ),
    ]
