# Generated by Django 5.2.5 on 2025-08-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_user_date_joined_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
