# Generated by Django 5.2.5 on 2025-08-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_user_phone_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=13, unique=True, verbose_name="phone number"
            ),
        ),
    ]
