# Generated by Django 5.2.5 on 2025-09-07 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="code",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="expires",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="otp",
            name="phone",
            field=models.CharField(max_length=13),
        ),
    ]
