# Generated by Django 5.2.5 on 2025-09-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_otp_code_otp_expires_alter_otp_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                verbose_name="phone number",
            ),
        ),
    ]
