# Generated by Django 5.2.5 on 2025-09-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
