# Generated by Django 5.2.5 on 2025-09-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="number",
            field=models.IntegerField(null=True),
        ),
    ]
